PL/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class ProductoController : Controller
    {

        // GET: Producto
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Producto producto = new ML.Producto();
            ML.Result result = new ML.Result();
            producto.Proovedor = new ML.Proovedor();

            ML.Result resultProovedor = BL.Proovedor.GetAll();
            result = BL.Producto.GetAll(producto);

            if (result.Correct)
            {
                producto.Proovedor.Proveedores = resultProovedor.Objects;
                producto.Productos = result.Objects;

                return View(producto);
            }
            else
            {
                ViewBag.Message = "Ocurrio un error";
                return View();
            }

        }

        [HttpPost]

        public ActionResult GetAll(ML.Producto producto)
        {
            ML.Result result = new ML.Result();
            //producto.Proovedor = new ML.Proovedor();

            ML.Result resultProovedor = BL.Proovedor.GetAll();
            result = BL.Producto.GetAll(producto);

            if (result.Correct)
            {

                producto.Productos = result.Objects;
                producto.Proovedor.Proveedores = resultProovedor.Objects;
                return View(producto);
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la Consulta";
                return View();
            }
        }

        [HttpGet]
        public ActionResult Form(int? IdProducto)
        {

            ML.Producto producto = new ML.Producto();

            producto.Departamento = new ML.Departamento();
            producto.Proovedor = new ML.Proovedor();
            producto.Departamento.Area = new ML.Area();


            ML.Result resultDepartamento = BL.Departamento.GetAll();
            ML.Result resultProveedor = BL.Proovedor.GetAll();
            ML.Result resultArea = BL.Area.GetAll();

            if (IdProducto == null)
            {
                //
                //producto.Rol.Roles = resultRol.Objects;
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                producto.Proovedor.Proveedores = resultProveedor.Objects;
                producto.Departamento.Area.Areas = resultArea.Objects;
                return View(producto);
            }
            else
            {

                //GetbyId
                ML.Result result = BL.Producto.GetById(IdProducto.Value);

                if (result.Correct)
                {
                    producto = (ML.Producto)result.Object;
                    producto.Departamento.Departamentos = resultDepartamento.Objects;
                    producto.Proovedor.Proveedores = resultProveedor.Objects;
                    producto.Departamento.Area.Areas = resultArea.Objects;


                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar el Usuario seleccionado";
                }
                return View(producto);
            }

        }

        [HttpPost]

        public ActionResult Form(ML.Producto producto)
        {

            IFormFile image = Request.Form.Files["IFImage"];


            //valido si traigo imagen
            if (image != null)
            {
                //llamar al metodo que convierte a bytes la imagen
                byte[] ImagenBytes = ConvertToBytes(image);
                //convierto a base 64 la imagen y la guardo en la propiedad de imagen en el objeto usuario
                producto.Imagen = Convert.ToBase64String(ImagenBytes);
            }

            if (!ModelState.IsValid)
            {
                //ML.Producto producto = new ML.Producto();

                producto.Departamento = new ML.Departamento();
                producto.Proovedor = new ML.Proovedor();
                producto.Departamento.Area = new ML.Area();


                ML.Result resultDepartamento = BL.Departamento.GetAll();
                ML.Result resultProveedor = BL.Proovedor.GetAll();
                ML.Result resultArea = BL.Area.GetAll();

                return View(producto);

            }
            else
            {

                if (producto.IdProducto == 0)
                {
                    ML.Result result = BL.Producto.Add(producto);
                    if (result.Correct)
                    {
                        ViewBag.Message = "Se ha registrado el producto";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Message = "No se ha registrado el Producto" + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
                else
                {
                    ML.Result result = BL.Producto.Update(producto);
                    if (result.Correct)
                    {

                        ViewBag.Message = "Se ha actualizado el Producto";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Message = "No ha actualizado el Producto" + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }
            }
        }

        [HttpGet]
        public ActionResult Delete(int IdProducto)
        {
            ML.Result result = new ML.Result();

            result = BL.Producto.Delete(IdProducto);
            if (result.Correct)
            {
                ViewBag.Message = "Se ha elimnado el registro";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Message = "No se ha elimnado el registro" + result.ErrorMessage;
                return PartialView("Modal");
            }
        }

        //Convertir imagen
        public static byte[] ConvertToBytes(IFormFile imagen)
        {

            using var fileStream = imagen.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, (int)fileStream.Length);

            return bytes;
        }


        public JsonResult GetDepartamento(int IdArea)
        {
            var result = BL.Departamento.DepartamentoGetByArea(IdArea);

            return Json(result.Objects);
        }

    }
}

PL/Views/Producto/Form.cshtml
@model ML.Producto
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Form</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <div class="col-md-3">

                        @Html.LabelFor(model => model.IdProducto, new { @class = "hidden" })

                        @Html.TextBoxFor(model => model.IdProducto, new { @class = "hidden form-control" })

                        @Html.ValidationMessageFor(model => model.IdProducto)

                    </div>

                    <div class="col-md-3">

                        @Html.LabelFor(model => model.Nombre)

                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @placeholder = "Ejemplo: Mochila" , autocomplete = "off"})

                        @Html.ValidationMessageFor(model => model.Nombre)

                    </div>
                </div>


                <div class="row">
                    <div class="col-md-3">

                        @Html.LabelFor(model => model.PrecioUnitario)

                        @Html.TextBoxFor(model => model.PrecioUnitario, new { @class = "form-control" , @placeholder ="Ejemplo: 600" , autocomplete = "off"})

                        @Html.ValidationMessageFor(model => model.PrecioUnitario)

                    </div>

                    <div class="col-md-3">

                        @Html.LabelFor(model => model.Stock)

                        @Html.TextBoxFor(model => model.Stock, new { @class = "form-control" , @placeholder ="20" , autocomplete = "off"})

                        @Html.ValidationMessageFor(model => model.Stock)

                    </div>
                </div>

                <hr></hr>
                <div class="divider py-1 bg-success"></div>

                <div class="row g-3">
                    <div class="col-md-3">

                        @Html.LabelFor(model => model.Proovedor.IdProovedor)

                        @*@Html.TextBoxFor(model => model.Proveedor.IdProovedor, new { @class = "form-control" })*@
                        @Html.DropDownListFor(model => model.Proovedor.IdProovedor, new SelectList(Model.Proovedor.Proveedores, "IdProovedor", "Nombre"), "Selecciona una opción", new { @class = "form-control" })

                        @Html.ValidationMessageFor(model => model.Proovedor.IdProovedor)

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">

                        @Html.LabelFor(model =>model.Departamento.Area.IdArea)

                        @Html.DropDownListFor(model => model.Departamento.Area.IdArea, new SelectList(Model.Departamento.Area.Areas, "IdArea", "Nombre"), "Selecciona una opcion", new{id="ddlArea", @class = "form-control"})

                        @Html.ValidationMessageFor(model => model.Departamento.Area.IdArea)
                    </div>

                    <div class="col-md-3">

                        @Html.LabelFor(model =>model.Departamento.IdDepartamento)
                        @if (Model.Departamento.Departamentos == null)
                        {
                            @Html.DropDownListFor(model =>model.Departamento.IdDepartamento, new SelectList(string.Empty, "Value", "Text"),"Seleciona un Departamento", htmlAttributes: new{id= "ddlDepartamento", @class="form-control"})
                            @Html.ValidationMessageFor(model => model.Departamento.IdDepartamento)
                        }
                        else
                        {
                            @Html.DropDownListFor(model =>model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Nombre"), "Selecciona un Departamento", htmlAttributes: new {id="ddlDepartamento", @class= "form-control"})
                            @Html.ValidationMessageFor(model => model.Departamento.IdDepartamento)
                        }


                    </div>

                </div>


                <div class="row">
                    <div class="col-md-3">

                        @Html.LabelFor(model => model.Descripcion)

                        @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", @placeholder ="Descripcion del producto" , autocomplete = "off"})

                        @Html.ValidationMessageFor(model => model.Descripcion)


                    </div>

                    <div class=" col-md-3">

                        @Html.LabelFor(model=> model.Imagen)

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="bi bi-card-image"></i></span>
                            <input id="IFImage" type='file' class="form-control" name="IFImage" onchange="validateFile(this), readURL(this);  " />
                        </div>
                    </div>

                    <div class="row col-mb-3" >

                        @if (Model.Imagen != null)
                        {

                            <img id="Img" src="data:image/*;base64,@Model.Imagen" style="width:250px ; height:250px" />

                        }
                        else
                        {
                            <img id="Img" src="~/SinFotoProducto.png" style="width:225px ; height:200px" />
                        }


                        @Html.HiddenFor(model => model.Imagen)
                    </div>
                </div>


                <div class="form-group">

                    <div class="col-md-3">

                        <input type="submit" value="Guardar" class="btn btn-success" />

                        @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })

                    </div>

                </div>
            }
        </div>
    </div>

</div>
@section Scripts{

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#ddlArea").change(function () {
                $("#ddlDepartamento").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetDepartamento")',
                    dataType: 'json',
                    data: { IdArea: $("#ddlArea").val() },
                    success: function (departamentos) {
                        $("#ddlDepartamento").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                        $.each(departamentos, function (i, departamentos) {
                            $("#ddlDepartamento").append('<option value="'
                                + departamentos.idDepartamento + '">'
                                + departamentos.nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
            })
        })
    </script>
}

PL/Views/Producto/GetAll.cshtml
@model ML.Producto

@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Productos</h2>

<div class="container">


    <div class="row">
        <div style="float:right">
            @Html.ActionLink("Agregar", "Form", "Producto", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    @using (Html.BeginForm("GetAll", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row align-items-start">
            <div class="col-md-3">
                @Html.DropDownListFor(model => model.Proovedor.IdProovedor, new SelectList(Model.Proovedor.Proveedores, "IdProovedor", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
            </div>

            <div class="col-md-3">
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre Del Producto" })
            </div>
            <div class="col-md-3">
                <input type="submit" value="Buscar" class="btn btn-success" />
            </div>
        </div>

    }
</div>


<table class="table table-hover table-bordered table-responsive" id="tblProducto">
    <thead>
        <tr>
            <th>Editar</th>
            <th class="visually-hidden">IdProducto</th>
            <th>Nombre</th>
            <th>Precio Unitario</th>
            <th>Stock</th>
            <th class="visually-hidden">IdProovedor</th>
            <th>Proovedor</th>
            <th class="visually-hidden">IdDepartamento</th>
            <th>Departamento</th>
            <th class="visually-hidden">IdArea</th>
            <th>Area</th>
            <th>Descripcion</th>
            <th>Imagen </th>
            <th>Delete</th>


        </tr>
    </thead>

    <tbody class="table table-dark table-hover table-bordered border-primary">
        @foreach (ML.Producto producto in Model.Productos)
        {
            <tr>
                <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Producto", new { IdProducto = producto.IdProducto})"><i class="bi bi-pencil-square"></i></a></td>
                <td class="visually-hidden">@producto.IdProducto</td>
                <td>@producto.Nombre</td>
                <td>@producto.PrecioUnitario</td>
                <td>@producto.Stock</td>

                <td class="visually-hidden">@producto.Proovedor.IdProovedor</td>
                <td>@producto.Proovedor.Nombre</td>

                <td class="visually-hidden">@producto.Departamento.IdDepartamento</td>
                <td>@producto.Departamento.Nombre</td>

                <td class="visually-hidden"> @producto.Departamento.Area.IdArea</td>
                <td>@producto.Departamento.Area.Nombre</td>

                <td>@producto.Descripcion</td>

                @if (producto.Imagen != null)
                {
                    <td><img src="data:image/jpeg;base64, @producto.Imagen" style="height:175px; width:200px;" /></td>

                }
                else
                {
                    <td><img id="Img" src="~/SinFotoProducto.png" style="width:175px ; height:150px" /></td>
                }

                <td class="text-center"><a class="btn btn-danger " href="@Url.Action("Delete", "Producto", new { IdProducto = producto.IdProducto })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="bi bi-trash-fill"></i></a></td>
            </tr>
        }
    </tbody>
</table>


@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblProducto').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });

    </script>

}

PL/Views/Producto/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>